"""
# ByteLevel BPE Scaling Experiments

## Summary

Full recipe for training and scaling tokenizer with different corpus sizes, vocabulary sizes, patterns,
and evaluating the trained tokenizers on a simple test set to analyze the trade-offs between:
- training corpus size,
- vocabulary size,
- split pattern,
- tokenization quality (compression ration, efficiency, etc.)
- and cross-language generalization (if we have multilingual evaluation sets).

The training data is generated by sampling from a mixture of sources, which can be customized by the user.

By default, the training data is sampled from a mixture of the following sources ([gpt_lab.tokenizer.corpus](./../src/gpt_lab/tokenizer/corpus.py)):
- English web text (from fineweb-edu)
- Multilingual web text (from fineweb-2)
- Maths text (from finemath-4plus)
- Python code (from codeparrot-clean)

To keep the same logic between the different runs, we create the training data once, store it on disk, and then use it for all the different runs.
This also allows us to analyze the impact of the corpus size without having to worry about the randomness of the data generation process.

The evaluation is done on the following datasets (eval_configs in the code):
- enwik8 (for English text)
- fineweb-edu (for English web text)
- fineweb-2 (for multilingual web text, with subsets for different languages)
- finemath-4plus (for math text)
- github-top-code (for Python code)

> [!WARNING]
> With it current implementation, the script may use the same samples for both training and evaluation,
which can lead to overfitting and an overestimation of the tokenizer's performance.
> However, the results obtained were quite poored compared to the baselines, given that I could not reach
the optimal memory budget for training the tokenizers.
> Hence, in case of future runs with **exceptionally good results**, it would be important to check whether
the training and evaluation samples are overlapping, and if so, to implement a proper train/eval
split to get a more accurate estimate of the tokenizer's performance.

## Usage

Use `gpt-lab experiment tokenizer-scaling --help`; see docs/cli.md.

## Aknowledgements:
This code is inspired by and has some code adapted from the following sources:
- The Hugging Face Tokenizers library (https://github.com/huggingface/tokenizers)
- The OpenAI tiktoken library (https://github.com/openai/tiktoken)
- nanochat tokenizer code (https://github.com/karpathy/nanochat) for the idea of using HF-training backend + tiktoken-inference backend for efficient training and evaluation of tokenizers.

## References:
1. Reddy, Varshini, et al. "How much is enough? the diminishing returns of tokenization training data." arXiv preprint arXiv:2502.20273 (2025).
2. Zouhar, Vilém, et al. "Tokenization and the noiseless channel." Proceedings of the 61st Annual Meeting of the Association for Computational Linguistics (Volume 1: Long Papers). 2023.
3. Tao, Chaofan, et al. "Scaling laws with vocabulary: Larger models deserve larger vocabularies." Advances in Neural Information Processing Systems 37 (2024): 114147-114179.
4. Karpathy, Andrej. "Let’s Build the GPT Tokenizer: A Complete Guide to Tokenization in LLMs. A text and code version of Karpathy’s famous tokenizer video." https://www.fast.ai/posts/2025-10-16-karpathy-tokenizers.html (2025).

Author: Arthur Testard (arthur.testard.pro@gmail.com)
Please cite this work if the code is helpful to you.
"""
from __future__ import annotations

from gpt_lab.tokenizer.tokenizer import Tokenizer
from gpt_lab.utils.schemas import TokenizerTrainerConfig, TokenizerConfig
from gpt_lab.tokenizer.corpus import TokenizerCorpus
from gpt_lab.utils.default import PAT_STR, TOKENIZERS_FOLDER, DATA_DIR
from gpt_lab.utils.logging import log0

import os
import math
import json
from pathlib import Path
import pickle, zipfile
import time
from tqdm import tqdm
from collections import Counter

from typing import List, Optional

import regex as re

import logging
logger = logging.getLogger(__name__)

_BASELINES = ["gpt2", "cl100k_base", "o200k_base"]

byte_per_doc = lambda max_byte: max(1, max_byte // 10_000) # Default to 1000 documents if not specified, adjust as needed

def run(args):
    from gpt_lab.utils.logging import init_logger
    from gpt_lab.utils.common import get_banner
    init_logger()
    get_banner(to_print=True)

    # initiate results storage
    # create results path if it doesn't exist
    # and backup existing file if it does to avoid overwriting/mixing previous results
    result_dir = Path(args.result_dir)
    meta_path = result_dir / 'meta.json'
    if args.resume and meta_path.exists():
        with meta_path.open() as handle:
            meta = json.load(handle)
    else:
        meta = {key: getattr(args, key) for key in (
            'seed', 'baselines', 'num_procs', 'vocab_sizes', 'pat_strs',
            'write_corpus', 'corpus_sizes_gb', 'compare_truncated_baselines',
            'corpus_temperature_alpha', 'corpus_dir',
        )}
    validate_settings(meta)
    prepare_result_dir(result_dir, resume=args.resume)
    exp_name = result_dir.stem
    if not meta_path.exists():
        with meta_path.open('w') as handle:
            json.dump(meta, handle, indent=4)

    # Solve args and configurations
    num_procs = min(os.cpu_count() or 1, 32) if meta.get("num_procs") is None else meta["num_procs"]

    vocab_sizes = [int(v) for v in meta.get("vocab_sizes", "50_000, 70_000, 100_000, 200_000").split(",")]
    patterns = { f"pat_str-{s.strip()}": PAT_STR.get(s.strip()) for s in meta.get("pat_strs", "gpt2").split(",") if s.strip() in PAT_STR } if meta.get("pat_strs") else {"pat_str-gpt2": PAT_STR["gpt2"]}
    corpus_sizes = [int(float(s) * 1024 * 1024 * 1024) for s in meta.get("corpus_sizes_gb", None).split(",")] if meta.get("corpus_sizes_gb") else None
    baselines = [ b.strip() for b in meta.get("baselines", ",".join(_BASELINES)).split(",") if b.strip() in _BASELINES ] if meta.get("baselines") else _BASELINES

    result_paths = load_all_result_paths(result_dir) if result_dir.exists() else []

    for baseline in baselines:
        if baseline not in result_paths:
            enc = Tokenizer.from_pretrained(baseline, source="tiktoken")
            evaluation = eval_tokenizer(enc)
            result = dict(
                vocab_size=enc.n_vocab,
                pattern=baseline,
                max_chars=None,
                config=None,
                training_time=None,
                corpus_size_mb=None,
                evaluation=evaluation,
                baseline=baseline,
            )
            store_single_result(result, result_dir / f"{baseline}.pkl")


    tokenizer_name = lambda vocab_size, max_char, p_str_name: f"{exp_name}-{int(vocab_size//1000)}k_maxchar-{max_char//1e6:.1f}M_pattern-{p_str_name}"

    log0(f"Using {num_procs} processes for tokenizer training.")
    corpus_path = Path(meta["corpus_dir"]) if meta.get("corpus_dir") else DATA_DIR / "corpus" / exp_name
    corpus_bytemax = max(corpus_sizes)

    if args.write_corpus:
        log0(f"Writing corpus to {corpus_path} with max bytes {corpus_bytemax:,}...", logger=logger)
        corpus = TokenizerCorpus.write_from_sources(
            corpus_dir=corpus_path,
            max_bytes=corpus_bytemax,
            bytes_per_doc=byte_per_doc(corpus_bytemax),
            random_seed=meta.get("seed"),
            temperature_alpha=meta.get("corpus_temperature_alpha"),
        )
        log0(f"Corpus written to {corpus_path}. Size: {sum(c.stat().st_size / 1e6 for c in corpus_path.glob('*.txt')):.2f} MB", logger=logger)

    if not args.write_corpus:
        log0(f"Using existing corpus at {corpus_path} with max bytes {corpus_bytemax:,} for tokenizer training.", logger=logger)
        if not corpus_path.exists():
            raise FileNotFoundError(f"Corpus path {corpus_path} does not exist. Please run the script with --write-corpus flag to create the corpus before training tokenizers.")
        corpus = TokenizerCorpus.from_path(corpus_path)
        corpus.show_stats()

    # selecting runs to execute based on the existing results and the configuration
    tasks = []
    for vocab_size in vocab_sizes:
        for p_str_name, p_str in patterns.items():
            for max_byte in corpus_sizes:
                name = tokenizer_name(vocab_size, max_byte, p_str_name)
                if name in result_paths:
                    log0(f"Skipping already completed run for vocab_size={vocab_size}, pattern={p_str_name}, max_byte={max_byte}.", logger=logger)
                    continue

                tasks.append(
                    (
                        name,
                        vocab_size,
                        p_str_name,
                        p_str,
                        max_byte,
                        corpus_path,
                        corpus_bytemax,
                        meta,
                    )
                )

    import multiprocessing as mp
    from concurrent.futures import ProcessPoolExecutor, as_completed

    mp.set_start_method("spawn", force=True)
    t_total_start = time.time()
    with ProcessPoolExecutor(max_workers=num_procs) as executor:
        future_to_name = {}
        futures = []
        for t in tasks:
            future = executor.submit(run_tokenizer_experiment, t)
            futures.append(future)
            future_to_name[future] = t[0]

        buffer = []
        for i, future in enumerate(tqdm(as_completed(futures), total=len(futures), desc="Tokenizer experiments")):
            result = future.result()
            run_name = future_to_name[future]
            buffer.append((result, run_name))

            if len(buffer) >= args.save_every:
                store_buffered_results(buffer, result_dir)

        if buffer:
            store_buffered_results(buffer, result_dir)
    total_time = time.time() - t_total_start

    log0(f"Total time for all runs: {total_time/3600:.2f} hours.", logger=logger)
    log0(f"All runs completed. Results stored in {result_dir}.", logger=logger)

def load_all_result_paths(result_dir: Path) -> List[str]:
    result_paths = []
    for path in result_dir.glob("*.pkl"):
        with open(path, "rb") as f:
            try:
                # check if the file is empty or corrupted
                result = pickle.load(f)
                if result is not None:
                    result_paths.append(path.stem)
            except EOFError:
                continue
    return result_paths

def _normalize_result_run_name(run_name: str) -> str:
    if not isinstance(run_name, str):
        raise ValueError("run_name must be a non-empty string filename")
    normalized_run_name = run_name.strip()
    if not normalized_run_name:
        raise ValueError("run_name must be a non-empty string filename")
    run_path = Path(normalized_run_name)
    if run_path.name != normalized_run_name or normalized_run_name in {".", ".."}:
        raise ValueError("run_name must be a filename without directory components")
    if run_path.suffix != ".pkl":
        normalized_run_name = f"{normalized_run_name}.pkl"
    return normalized_run_name

def store_single_result(result, path):
    with open(path, "wb") as f:
        pickle.dump(result, f)

def store_buffered_results(buffer, result_dir):
    for result, run_name in buffer:
        safe_run_name = _normalize_result_run_name(run_name)
        path = result_dir / safe_run_name
        store_single_result(result, path)
    buffer.clear()

def renyi_entropy(counter, alpha=2.5, eps=1e-12):
    """
    Rényi entropy of order alpha as proposed by Zouhar et al. (2023) to measure the diversity of the corpus.
    """
    total = sum(counter.values())
    if total == 0:
        return 0.0
    probabilities = [count / total for count in counter.values()]
    if alpha == 1:
        return -sum(p * math.log(p) for p in probabilities)
    else:
        return (1 / (1 - alpha)) * math.log(sum(p ** alpha for p in probabilities))

def entropy_efficiency(counter, alpha=2.5, eps=1e-12):
    """
    Efficiency of the tokenizer as proposed by Zouhar et al. (2023), defined as
    the ratio of the Rényi entropy of the token distribution to the logarithm of
    the vocabulary size.

    This metric captures how well the tokenizer utilizes its vocabulary to represent
    the diversity of the corpus. A higher efficiency indicates that the tokenizer is
    effectively using its vocabulary to capture the variability in the data, while a
    lower efficiency may suggest that many tokens are underutilized or that the tokenizer
    is not capturing enough diversity.
    """
    vocab_size = len(counter)
    if vocab_size == 0:
        return 0.0
    renyi_ent = renyi_entropy(counter, alpha=alpha, eps=eps)
    return renyi_ent / math.log(vocab_size)


def get_eval_corpus(eval_set):
    return TokenizerCorpus.from_sources(
        corpus_dir=eval_set["localdir"],
        sources=[eval_set["generator_source"]],
        # max_chars=500_000, # just for evaluation, we can use a subset of the data
        max_bytes=500_000 * 4, # just for evaluation, we can use a subset of the data, adjust as needed based on your corpus
        bytes_per_doc=4096 * 4,
        split=eval_set["split"],
        compressed=True,
        shard_size_bytes=50_000 * 4,
        loader_fn=eval_set.get("loader_fn", None), # will overwrite for enwik8
    )

def eval_tokenizer(tokenizer):
    results = {}
    _counter = Counter()
    _token_len_cache = {}
    for tok in tokenizer.mergeable_ranks.values():
        _token_len_cache[tok] = len(
            tokenizer.decode_single_token_bytes(tok)
        )
    for eval_set in eval_sets:
        metrics = dict()
        _counter = Counter()
        len_tokens = 0
        len_chars = 0
        len_bytes = 0
        corpus = get_eval_corpus(eval_set).iterator()
        t0 = time.time()
        for text in corpus:
            if not text.strip():
                continue
            tokens = tokenizer.encode(text, disallowed_special=())
            len_tokens += len(tokens)
            len_chars += len(text)
            len_bytes += len(text.encode("utf-8"))
            decoded = tokenizer.decode(tokens)
            acc = decoded == text
            compression_ratio = len(tokens) / len(text) if len(text) > 0 else 0
            tokens_per_bytes = len(tokens) / len_bytes
            # maybe optimized
            char_by_token = [_token_len_cache[tok] for tok in tokens]
            char_by_token_avg = sum(char_by_token) / len(char_by_token) if len(char_by_token) > 0 else 0
            for key, value in [
                ("accuracy", acc),
                ("compression_ratio", compression_ratio),
                ("tokens_per_bytes", tokens_per_bytes),
                ("nb_char_by_token_avg", char_by_token_avg)
                ]:
                if key not in metrics:
                    metrics[key] = []
                metrics[key].append(value)
        t1 = time.time()
        res = {key: sum(values) / len(values) for key, values in metrics.items()}
        # both are useless actually as we store the counter and can compute any metric we want from it,
        # but let's keep them for now as they are easy to compute and can be a quick proxy
        res["renyi_entropy"] = renyi_entropy(_counter)
        res["entropy_efficiency"] = entropy_efficiency(_counter)
        res["nb_tokens"] = len_tokens
        res["nb_chars"] = len_chars
        res["nb_bytes"] = len_bytes
        # NOTE: probably too heavy to store the counter for all the runs
        # res["token_counter"] = counter
        res["eval_time"] = t1 - t0
        results[eval_set["metricname"]] = res
    return results

def compare_with_truncated_baselines(target_vocab_size):
    comparisons = {}
    from tiktoken import get_encoding

    for baseline in _BASELINES:
        baseline_vocab_size = get_encoding(baseline).n_vocab
        if baseline_vocab_size <= target_vocab_size:
            continue

        truncated_name = f"{baseline}_truncated_{target_vocab_size}"
        truncated_tokenizer = Tokenizer.truncated_from_pretrained(baseline, target_vocab_size)
        comparisons[baseline] = {
            "base_vocab_size": baseline_vocab_size,
            "truncated_name": truncated_name,
            "evaluation": eval_tokenizer(truncated_tokenizer),
        }

    return comparisons


# --------------------------------------------------------------------
# Parallel execution of tokenizer training and evaluation
# --------------------------------------------------------------------

def run_tokenizer_experiment(task):
    (
        name,
        vocab_size,
        p_str_name,
        p_str,
        max_bytes,
        corpus_path,
        corpus_bytemax,
        meta
    ) = task
    num_procs = 1  # IMPORTANT: avoid nested parallelism
    corpus = TokenizerCorpus.from_path(corpus_path)
    trainer_config = TokenizerTrainerConfig(
        max_bytes=max_bytes,
        bytes_per_doc=max(1, max_bytes // 20_000),
        num_proc=num_procs,
        source="huggingface",
        dircorpus=corpus_path, # TODO: add CorpusConfig instead
        show_progress=False,
        to_save=False,
    )
    config = TokenizerConfig(
        name=name,
        vocab_size=vocab_size,
        pat_str=p_str,
        source="huggingface", # this is quite dummy
        save_token_bytes=False, # we will compute token bytes on the fly without saving to disk to avoid IO overhead, adjust as needed based on your use case and whether you want to inspect the token bytes files
        # special_tokens=SpecialTokens(), # using default special tokens, adjust as needed
        trainer=trainer_config,
    )
    t0 = time.time()
    tokenizer = Tokenizer.train_from_iterator(
        text_iterator=corpus.iterator(max_bytes=max_bytes),
        config=config,
    )
    t1 = time.time()

    result = {
        "vocab_size": vocab_size,
        "pattern": p_str_name,
        "max_bytes": max_bytes,
        "tokenizer_name": name,
        "config": str(config),
        "training_time": t1 - t0,
        "corpus_size_gb": sum(path.stat().st_size for path in corpus.shard_paths()) / 1e9,
    }

    for text in corpus.iterator(max_bytes=max_bytes):
        result["nb_chars_trained"] = result.get("nb_chars_trained", 0) + len(text)
        result["nb_words_trained"] = result.get("nb_words_trained", 0) + len(text.split())
        result["nb_bytes_trained"] = result.get("nb_bytes_trained", 0) + len(text.encode("utf-8"))
        result["nb_subwords_trained"] = result.get("nb_subwords_trained", 0) + len(re.findall(config.pat_str, text))
        result["nb_tokens_trained"] = result.get("nb_tokens_trained", 0) + len(tokenizer.encode(text, disallowed_special=()))

    result["evaluation"] = eval_tokenizer(tokenizer)
    if meta.get("compare_truncated_baselines"):
        result["truncated_baselines"] = compare_with_truncated_baselines(vocab_size)

    del tokenizer
    return result

# --------------------------------------------------------------------
# Prepare evaluation sets configurations and loaders
# --------------------------------------------------------------------

def enwik8_path():
    base_dir = DATA_DIR / "corpus/eval_enwik8"
    base_dir.mkdir(parents=True, exist_ok=True)
    # download and unzip enwik8 to cache directory
    enwik8_url = "https://mattmahoney.net/dc/enwik8.zip"
    enwik8_local_path = base_dir.joinpath("enwik8")
    enwik8_local_path_zip = base_dir.joinpath("enwik8.zip")
    if not enwik8_local_path.exists():
        log0(f"Downloading enwik8 to {enwik8_local_path_zip}", logger=logger)
        import requests
        response = requests.get(enwik8_url)
        with open(enwik8_local_path_zip, "wb") as f:
            f.write(response.content)
        with zipfile.ZipFile(enwik8_local_path_zip, "r") as zip_ref:
            zip_ref.extractall(base_dir)
        log0(f"Unzipped enwik8 to {enwik8_local_path}", logger=logger)
        enwik8_local_path_zip.unlink()
        log0(f"Removed {enwik8_local_path_zip}", logger=logger)
    else:
        log0(f"Using existing enwik8 at {enwik8_local_path}", logger=logger)
    return enwik8_local_path


def enwik8_loader():
    with open(enwik8_path(), "r", encoding="utf-8") as f:
        return f.read(10**7).split("\n")

eval_configs = {
    "enwik8": dict(
        loader_fn=enwik8_loader,
    ),
    "HuggingFaceFW/fineweb-edu": dict(
        split="train" # no test or validation split available
    ),
    "HuggingFaceTB/finemath": dict(
        split="train",
        name=["finemath-3plus"]
    ),
    "ronantakizawa/github-top-code": dict(
        filter_fn=lambda x: x["file_language"] == "Python" # filter for python files only
    ),
    "HuggingFaceFW/fineweb-2": dict(
        name=["fra_Latn", "jpn_Jpan", "kor_Hang", "arb_Arab"],
    )
}
eval_sets = []
# prepare config to match the expected input of TokenizerCorpus.from_sources
for ds_name, ds_config in eval_configs.items():
    _ds = dict(name=ds_name)
    _ds["split"] = ds_config.get("split", "test")
    _ds["loader_fn"] = ds_config.get("loader_fn", None)
    _ds["generator_source"] = dict(path=ds_name, weight=1.0)
    if "filter_fn" in ds_config:
        _ds["generator_source"]["filter_fn"] = ds_config["filter_fn"]
    if ds_config.get("name", []) == []:
        _ds["localdir"] = DATA_DIR / f"corpus/eval_{ds_name.replace('/', '_')}"
        _ds["metricname"] = f"{ds_name.split('/')[-1]}"
        eval_sets.append(_ds)
    else:
        for name in ds_config["name"]:
            _ds = _ds.copy()
            _ds["generator_source"] = _ds["generator_source"].copy() # have to copy to avoid mutating the original for the next iteration
            _ds["subset"] = name
            _ds["localdir"] = DATA_DIR / f"corpus/eval_{ds_name.replace('/', '_')}:{name}"
            _ds["generator_source"]["name"] = name
            _ds["metricname"] = f"{ds_name.split('/')[-1]}:{name}"
            eval_sets.append(_ds)



def validate_settings(meta):
    sizes = meta.get('corpus_sizes_gb')
    if not sizes:
        raise ValueError('--corpus-sizes-gb is required for a new experiment (or in saved resume metadata); no automatic range is implemented')
    for key in ('corpus_sizes_gb', 'vocab_sizes'):
        converter = float if key == 'corpus_sizes_gb' else int
        values = [converter(value) for value in meta[key].split(',')]
        if not values or any(not math.isfinite(value) or value <= 0 for value in values):
            raise ValueError(f'{key} must be a comma-separated list of positive finite values')
    if any(float(value) * 1024**3 < 1 for value in sizes.split(',')):
        raise ValueError('--corpus-sizes-gb must request at least one byte per corpus')
    if meta.get('num_procs') is not None and meta['num_procs'] <= 0:
        raise ValueError('--num-procs must be positive')
    if meta.get('pat_strs'):
        unknown = set(value.strip() for value in meta['pat_strs'].split(',')) - PAT_STR.keys()
        if unknown:
            raise ValueError(f'Unknown pattern names: {sorted(unknown)}')
    if meta.get('baselines'):
        unknown = set(value.strip() for value in meta['baselines'].split(',')) - set(_BASELINES)
        if unknown:
            raise ValueError(f'Unknown baseline names: {sorted(unknown)}')


def prepare_result_dir(result_dir: Path, resume: bool) -> None:
    """Resume in place or preserve existing results under a numbered sibling."""
    if result_dir.exists() and not resume:
        index = 1
        backup = result_dir.with_name(f'{result_dir.name}_{index}')
        while backup.exists():
            index += 1
            backup = result_dir.with_name(f'{result_dir.name}_{index}')
        result_dir.rename(backup)
    result_dir.mkdir(parents=True, exist_ok=resume)
