report_template = """
Model Training Report

---------------------
Model Configuration:
---------------------
Model Type: {model_type}
Number of Parameters: {num_parameters}
Number of Layers: {num_layers}
Model Dimension: {dim_model}
Feedforward Dimension: {dim_ffn}
Number of Attention Heads: {num_heads}
Dropout Rate: {dropout}
Flash Attention Enabled: {flash_attention}
---------------------
Training Configuration:
Batch Size: {batch_size}
Learning Rate: {learning_rate}
Weight Decay: {weight_decay}
Optimizer: {optimizer}
---------------------
Total Training Time: {total_time:.2f} seconds
Total Epochs: {total_epochs}
Final Training Loss: {final_train_loss:.4f}
Final Training Accuracy: {final_train_accuracy:.4f}
Final Validation Loss: {final_val_loss:.4f}
Final Validation Accuracy: {final_val_accuracy:.4f}

Generated by MichelGPT
"""